# Generated by Django 2.0.7 on 2018-08-07 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0003_question_ulb'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='crn_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='crn no'),
            preserve_default=False,
        ),
    ]
