# Generated by Django 2.0.7 on 2018-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0005_question_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(choices=[('spandan', 'spandan'), ('gouse', 'gouse')], max_length=200, verbose_name='CCC EMPLOYEE'),
        ),
    ]
