# Generated by Django 2.0.7 on 2018-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0006_auto_20180807_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='District',
            field=models.CharField(choices=[('EAST GODAVARI', 'EAST GODAVARI'), ('WEST GODAVARI', 'WEST GODAVARI')], max_length=200, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='question',
            name='crn_no',
            field=models.CharField(max_length=200, verbose_name='CRN NO'),
        ),
    ]
