# Generated by Django 2.1 on 2018-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0007_auto_20180807_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='complaint_type',
            field=models.CharField(choices=[('desiling of drain', 'desiling of drain'), ('stagnation of water', 'stagnation of water')], max_length=200, verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ulb',
            field=models.CharField(choices=[('AMALAPURAM', 'AMALAPURAM'), ('KAKINADA', 'KAKINADA'), ('BHIMAVARAM', 'BHIMAVARAM'), ('ELURU', 'ELURU')], max_length=200, verbose_name='ULB'),
        ),
    ]
