# Generated by Django 2.1 on 2018-08-09 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0008_auto_20180808_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='Status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Completed', 'Completed')], default=django.utils.timezone.now, max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
