# Generated by Django 2.1 on 2018-08-09 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0009_auto_20180809_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.CharField(choices=[('EENADU', 'EENADU'), ('SAKSHI', 'SAKSHI')], default=django.utils.timezone.now, max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
