# Generated by Django 2.1 on 2018-08-09 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0010_question_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='Status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=200, verbose_name='Status'),
        ),
    ]
