# Generated by Django 2.1 on 2018-08-09 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0012_auto_20180809_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Closed Date'),
            preserve_default=False,
        ),
    ]
