# Generated by Django 2.0.7 on 2018-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0014_auto_20180811_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.IntegerField(null='True', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=200, null='True', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='question',
            name='phone',
            field=models.IntegerField(null='True', verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='question',
            name='typee',
            field=models.IntegerField(null='True', verbose_name='Type'),
        ),
    ]
