# Generated by Django 2.0.7 on 2018-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0015_auto_20180813_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='crn',
            field=models.CharField(max_length=200, null='True', verbose_name='CRN'),
        ),
        migrations.AlterField(
            model_name='question',
            name='typee',
            field=models.CharField(max_length=200, null='True', verbose_name='Type'),
        ),
    ]
