# Generated by Django 2.0.7 on 2018-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0016_auto_20180815_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null='True', verbose_name='Status'),
        ),
    ]
