# Generated by Django 2.0.7 on 2018-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0017_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ulbname',
            field=models.CharField(max_length=200, null='True', verbose_name='Type'),
        ),
    ]
