# Generated by Django 2.0.7 on 2018-08-15 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0018_question_ulbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='ulbname',
            field=models.CharField(max_length=200, null='True', verbose_name='ulb'),
        ),
    ]
