# Generated by Django 2.0.7 on 2018-08-15 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0019_auto_20180815_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data1',
        ),
        migrations.AddField(
            model_name='question',
            name='date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='DateTime'),
        ),
    ]
