# Generated by Django 2.0.7 on 2018-08-15 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0020_auto_20180815_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date1',
        ),
        migrations.AddField(
            model_name='question',
            name='frm',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Registed On'),
        ),
        migrations.AddField(
            model_name='question',
            name='to',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Completed On'),
        ),
    ]
