# Generated by Django 2.0.7 on 2018-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0021_auto_20180815_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='to',
            field=models.DateTimeField(blank=True, verbose_name='Completed On'),
        ),
    ]
