# Generated by Django 2.0.7 on 2018-08-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0022_auto_20180815_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='to',
            field=models.DateTimeField(blank=True, null='True', verbose_name='Completed On'),
        ),
    ]
