# Generated by Django 2.1 on 2018-08-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse', '0023_auto_20180816_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='distr',
            field=models.CharField(blank=True, max_length=200, null='True', verbose_name='District'),
            preserve_default='True',
        ),
    ]
